theme: minima
title: Blog do Eduardo Genes
description: Dicas de programação, cloud, esportes e um pouco da vida real!
author: eduardogenes

email: eduardogenes95@email.com
twitter_username: genespontodev
github_username: eduardogenes
linkedin_username: eduardogenes
